// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbsmlwqhmmjwlwyeefmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic21sd3FobW1qd2x3eWVlZm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTgzOTEsImV4cCI6MjA1Nzc3NDM5MX0.bI1IxvPEeKXt-3X13tnrNwl3s6H0K7JRTn3knwgtc40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);